### ISSUE TITLE
Last Run End should show the completed last run end

### ISSUE THREAD

**Issue by pathikrit** [coatue/airflow#111]
![image](https://user-images.githubusercontent.com/899219/66506423-4f227700-ea9b-11e9-928f-1e7613b8e65f.png)

The yellow button above is good enough, it is redundant to show currently running twice... The last run end should always show the last time something ended

**Comment by skim-coatue** [comment]
resolved by https://github.com/coatue/airflow/pull/113

**Comment by pathikrit** [comment]
This does not work:
![image](https://user-images.githubusercontent.com/899219/70283153-3928ee00-178e-11ea-8883-24965ac3cadb.png)

**Comment by skim-coatue** [comment]
Ha I forgot all about this and reverted the change in my last PR bc I thought it was a bug. One line fix
