### ISSUE TITLE
Button to Kill Currently Running Batch Job

### ISSUE THREAD

**Issue by nzheng-coatue** [coatue/airflow#144]
Right now you need to go to the running task and mark as failure. As we are getting rid of all of that with https://github.com/coatue/airflow/issues/140, we need a kill currently running batch task.

**Comment by pathikrit** [comment]
When you kill a batch job, BatchOperator sends termination to batch already. If you are using APIs yourself from application code to create batch jobs, its your responsbility to kill them. And you are an idiot.
