### ISSUE TITLE
MS master UI nit list

### ISSUE THREAD

**Issue by maxscheiber** [coatue/airflow#53]
The default UI is, to say the least, cluttered. It doesn't optimize for 1) organization of tasks by theme/dataset, or 2) quick processing of status information.

- [x] **very important** grouping of tasks by theme, similar to TeamCity. we have hundreds of tasks and different people care about different ones
- [x] **very important** link to source of truth definition of job schedule and job definition in GitHub. a common operation for research is to edit the job schedule or edit the Slack channel it points to.
- [x] **very important** reduce width of rows. be able to show more rows on a screen so we can scroll less. most of these sub-tables do not need to exist.
- [ ] **important** human-readable job names (i.e. not lowercase DAG)
- [x] remove "original config" section -- it seems to contain no information?
- [x] "recent tasks" view is not really intuitive to me. why does it only show one run for most of these tasks? what is it even supposed to represent?

**Comment by pathikrit** [comment]
All except "human readable job names" is done. The "human readable job name" is a WONTFIX because of a combination of how hard it is (need to modify the core airflow tables and model objects) compared to the benefits.
