### ISSUE TITLE
UI search is broken when nested

### ISSUE THREAD

**Issue by maxscheiber** [coatue/airflow#56]
Once you've searched for a DAG, you have to explicitly go back to the homepage or clear the search bar to search for other DAGs. This is super, super annoying.

**From the home page, everything is fine**
![image](https://user-images.githubusercontent.com/1323070/64715060-c4476000-d48d-11e9-84f9-a629f20504ed.png)

**Now I can't see other IHS DAGs**
![image](https://user-images.githubusercontent.com/1323070/64715065-c6a9ba00-d48d-11e9-8146-c4700ba7e93c.png)

**more DAGs I can't see**
![image](https://user-images.githubusercontent.com/1323070/64715089-d6c19980-d48d-11e9-89e7-ed6f1fc2880e.png)

**Comment by pathikrit** [comment]
* [ ] Make search global irrespective of what's displayed
* [ ] Show all results if search string length >2
* [ ] Make a single enter show only jobs matching the search string
