### ISSUE TITLE
Human readable cron hover display - Issue 5

### ISSUE THREAD

**Issue by awong-coatue** [coatue/airflow#82]
We would like the cron field to be a human readable field. This is a usability feature. 

Priority: Low

**Comment by awong-coatue** [comment]
Migrated from https://github.com/coatue/airflow-fork/issues/21

**Comment by pathikrit** [comment]
This is broken: 
![image](https://user-images.githubusercontent.com/899219/69684713-a8fcf180-1087-11ea-8926-fbacb34a25c1.png)
